HEROES = {
    "Aldous": {"lane": "exp", "role": "fighter", "region": "agelta"},
    "Alice": {"lane": "exp", "role": "tank", "region": "abyss"},
    "Argus": {"lane": "exp", "role": "fighter", "region": "abyss"},
    "Arlott": {"lane": "exp", "role": "fighter", "region": "moniyan"},
    "Badang": {"lane": "exp", "role": "fighter", "region": "vonetis"},
    "Benedetta": {"lane": "exp", "role": "assassin", "region": "barren"},
    "Chou": {"lane": "exp", "role": "fighter", "region": "agelta"},
    "Cici": {"lane": "exp", "role": "fighter", "region": "moniyan"},
    "Dyrroth": {"lane": "exp", "role": "fighter", "region": "abyss"},
    "Edith": {"lane": "exp", "role": "tank", "region": "vonetis"},
    "Esmeralda": {"lane": "exp", "role": "mage", "region": "agelta"},
    "Freya": {"lane": "exp", "role": "fighter", "region": "northern"},
    "Gloo": {"lane": "exp", "role": "tank", "region": "azrya"},
    "Guinevere": {"lane": "exp", "role": "fighter", "region": "moniyan"},
    "Lapu-Lapu": {"lane": "exp", "role": "fighter", "region": "vonetis"},
    "Masha": {"lane": "exp", "role": "tank", "region": "northern"},
    "Paquito": {"lane": "exp", "role": "fighter", "region": "barren"},
    "Ruby": {"lane": "exp", "role": "fighter", "region": "moniyan"},
    "Sun": {"lane": "exp", "role": "fighter", "region": "cadia"},
    "Thamuz": {"lane": "exp", "role": "fighter", "region": "abyss"},
    "Uranus": {"lane": "exp", "role": "tank", "region": "vonetis"},
    "X.Borg": {"lane": "exp", "role": "fighter", "region": "agelta"},
    "Yu Zhong": {"lane": "exp", "role": "fighter", "region": "cadia"},
    "Zilong": {"lane": "exp", "role": "fighter", "region": "cadia"},

    "Fanny": {"lane": "jungle", "role": "assassin", "region": "moniyan"},
    "Ling": {"lane": "jungle", "role": "assassin", "region": "cadia"},
    "Hayabusa": {"lane": "jungle", "role": "assassin", "region": "cadia"},
    "Gusion": {"lane": "jungle", "role": "assassin", "region": "moniyan"},
    "Lancelot": {"lane": "jungle", "role": "assassin", "region": "moniyan"},
    "Karina": {"lane": "jungle", "role": "assassin", "region": "azrya"},
    "Helcurt": {"lane": "jungle", "role": "assassin", "region": "abyss"},
    "Hanzo": {"lane": "jungle", "role": "assassin", "region": "cadia"},
    "Julian": {"lane": "jungle", "role": "assassin", "region": "moniyan"},
    "Joy": {"lane": "jungle", "role": "assassin", "region": "azrya"},

    "Eudora": {"lane": "mid", "role": "mage", "region": "northern"},
    "Kagura": {"lane": "mid", "role": "mage", "region": "cadia"},
    "Lunox": {"lane": "mid", "role": "mage", "region": "agelta"},
    "Xavier": {"lane": "mid", "role": "mage", "region": "moniyan"},
    "Vale": {"lane": "mid", "role": "mage", "region": "agelta"},
    "Valir": {"lane": "mid", "role": "mage", "region": "agelta"},
    "Yve": {"lane": "mid", "role": "mage", "region": "vonetis"},
    "Zhask": {"lane": "mid", "role": "mage", "region": "agelta"},

    "Layla": {"lane": "gold", "role": "marksman", "region": "agelta"},
    "Miya": {"lane": "gold", "role": "marksman", "region": "azrya"},
    "Lesley": {"lane": "gold", "role": "marksman", "region": "moniyan"},
    "Claude": {"lane": "gold", "role": "marksman", "region": "agelta"},
    "Beatrix": {"lane": "gold", "role": "marksman", "region": "agelta"},
    "Wanwan": {"lane": "gold", "role": "marksman", "region": "cadia"},
    "Moskov": {"lane": "gold", "role": "marksman", "region": "agelta"},

    "Tigreal": {"lane": "roam", "role": "tank", "region": "moniyan"},
    "Franco": {"lane": "roam", "role": "tank", "region": "northern"},
    "Atlas": {"lane": "roam", "role": "tank", "region": "northern"},
    "Khufra": {"lane": "roam", "role": "tank", "region": "agelta"},
    "Lolita": {"lane": "roam", "role": "tank", "region": "agelta"},
    "Johnson": {"lane": "roam", "role": "tank", "region": "agelta"},

    "Angela": {"lane": "roam", "role": "support", "region": "agelta"},
    "Estes": {"lane": "roam", "role": "support", "region": "azrya"},
    "Rafaela": {"lane": "roam", "role": "support", "region": "moniyan"},
    "Mathilda": {"lane": "roam", "role": "support", "region": "agelta"},
    "Floryn": {"lane": "roam", "role": "support", "region": "agelta"},
}
