HEROES = {
  "Aamon": {"lane": ["Jungle"], "role": ["Assassin"], "region": "Moniyan"},
  "Akai": {"lane": ["Roam"], "role": ["Tank"], "region": "Cadia Riverlands"},
  "Aldous": {"lane": ["EXP"], "role": ["Fighter"], "region": "Agelta Drylands"},
  "Alice": {"lane": ["EXP"], "role": ["Mage", "Tank"], "region": "Abyss"},
  "Alpha": {"lane": ["Jungle"], "role": ["Fighter"], "region": "Agelta Drylands"},
  "Alucard": {"lane": ["Jungle"], "role": ["Assassin", "Fighter"], "region": "Moniyan"},
  "Angela": {"lane": ["Roam"], "role": ["Support"], "region": "Agelta Drylands"},
  "Argus": {"lane": ["EXP"], "role": ["Fighter"], "region": "Abyss"},
  "Arlott": {"lane": ["EXP"], "role": ["Assassin", "Fighter"], "region": "Moniyan"},
  "Atlas": {"lane": ["Roam"], "role": ["Tank"], "region": "Northern Vale"},
  "Aulus": {"lane": ["Jungle"], "role": ["Fighter"], "region": "The Barren Lands"},
  "Aurora": {"lane": ["Mid"], "role": ["Mage"], "region": "Northern Vale"},
  "Badang": {"lane": ["EXP"], "role": ["Fighter"], "region": "Vonetis Sea"},
  "Balmond": {"lane": ["Jungle"], "role": ["Fighter"], "region": "The Barren Lands"},
  "Bane": {"lane": ["Jungle", "Mid"], "role": ["Fighter", "Mage"], "region": "Northern Vale"},
  "Barats": {"lane": ["Jungle"], "role": ["Fighter", "Tank"], "region": "Agelta Drylands"},
  "Baxia": {"lane": ["Jungle"], "role": ["Tank"], "region": "Cadia Riverlands"},
  "Beatrix": {"lane": ["Gold"], "role": ["Marksman"], "region": "Agelta Drylands"},
  "Belerick": {"lane": ["Roam"], "role": ["Tank"], "region": "Agelta Drylands"},
  "Benedetta": {"lane": ["EXP"], "role": ["Assassin", "Fighter"], "region": "The Barren Lands"},
  "Brody": {"lane": ["Gold"], "role": ["Marksman"], "region": "The Barren Lands"},
  "Bruno": {"lane": ["Gold"], "role": ["Marksman"], "region": "Agelta Drylands"},
  "Carmilla": {"lane": ["Roam"], "role": ["Support", "Tank"], "region": "Moniyan"},
  "Cecilion": {"lane": ["Mid"], "role": ["Mage"], "region": "Moniyan"},
  "Chang'e": {"lane": ["Mid"], "role": ["Mage"], "region": "Cadia Riverlands"},
  "Chip": {"lane": ["Roam"], "role": ["Support", "Tank"], "region": "Agelta Drylands"},
  "Chou": {"lane": ["EXP"], "role": ["Fighter"], "region": "Agelta Drylands"},
  "Cici": {"lane": ["EXP"], "role": ["Fighter"], "region": "Moniyan"},
  "Claude": {"lane": ["Gold"], "role": ["Marksman"], "region": "Agelta Drylands"},
  "Clint": {"lane": ["Gold"], "role": ["Marksman"], "region": "Agelta Drylands"},
  "Cyclops": {"lane": ["Mid"], "role": ["Mage"], "region": "Vonetis Sea"},
  "Diggie": {"lane": ["Roam"], "role": ["Support"], "region": "Agelta Drylands"},
  "Dyrroth": {"lane": ["EXP"], "role": ["Fighter"], "region": "Abyss"},
  "Edith": {"lane": ["EXP"], "role": ["Tank", "Marksman"], "region": "Vonetis Sea"},
  "Esmeralda": {"lane": ["EXP"], "role": ["Mage", "Tank"], "region": "Agelta Drylands"},
  "Estes": {"lane": ["Roam"], "role": ["Support"], "region": "Azrya Woodlands"},
  "Eudora": {"lane": ["Mid"], "role": ["Mage"], "region": "Northern Vale"},
  "Fanny": {"lane": ["Jungle"], "role": ["Assassin"], "region": "Moniyan"},
  "Faramis": {"lane": ["Mid"], "role": ["Mage", "Support"], "region": "The Barren Lands"},
  "Floryn": {"lane": ["Roam"], "role": ["Support"], "region": "Agelta Drylands"},
  "Franco": {"lane": ["Roam"], "role": ["Tank"], "region": "Northern Vale"},
  "Fredrinn": {"lane": ["Jungle"], "role": ["Fighter", "Tank"], "region": "Agelta Drylands"},
  "Freya": {"lane": ["EXP"], "role": ["Fighter"], "region": "Northern Vale"},
  "Gatotkaca": {"lane": ["Roam"], "role": ["Fighter", "Tank"], "region": "Vonetis Sea"},
  "Gloo": {"lane": ["EXP"], "role": ["Tank"], "region": "Azrya Woodlands"},
  "Gord": {"lane": ["Mid"], "role": ["Mage"], "region": "Northern Vale"},
  "Granger": {"lane": ["Gold"], "role": ["Marksman"], "region": "Moniyan"},
  "Grock": {"lane": ["Roam"], "role": ["Fighter", "Tank"], "region": "The Barren Lands"},
  "Guinevere": {"lane": ["EXP"], "role": ["Fighter"], "region": "Moniyan"},
  "Gusion": {"lane": ["Jungle"], "role": ["Assassin"], "region": "Moniyan"},
  "Hanabi": {"lane": ["Gold"], "role": ["Marksman"], "region": "Cadia Riverlands"},
  "Hanzo": {"lane": ["Jungle"], "role": ["Assassin"], "region": "Cadia Riverlands"},
  "Harith": {"lane": ["Gold"], "role": ["Mage"], "region": "Moniyan"},
  "Harley": {"lane": ["Jungle"], "role": ["Assassin", "Mage"], "region": "Northern Vale"},
  "Hayabusa": {"lane": ["Jungle"], "role": ["Assassin"], "region": "Cadia Riverlands"},
  "Helcurt": {"lane": ["Jungle"], "role": ["Assassin"], "region": "Abyss"},
  "Hilda": {"lane": ["Roam"], "role": ["Fighter", "Tank"], "region": "Northern Vale"},
  "Hylos": {"lane": ["Roam"], "role": ["Tank"], "region": "Agelta Drylands"},
  "Irithel": {"lane": ["Gold"], "role": ["Marksman"], "region": "Azrya Woodlands"},
  "Ixia": {"lane": ["Gold"], "role": ["Marksman"], "region": "Agelta Drylands"},
  "Jawhead": {"lane": ["Roam"], "role": ["Fighter"], "region": "The Barren Lands"},
  "Johnson": {"lane": ["Roam"], "role": ["Tank", "Support"], "region": "Agelta Drylands"},
  "Joy": {"lane": ["Jungle"], "role": ["Assassin"], "region": "Azrya Woodlands"},
  "Julian": {"lane": ["Jungle"], "role": ["Assassin", "Fighter"], "region": "Moniyan"},
  "Kadita": {"lane": ["Mid"], "role": ["Mage", "Assassin"], "region": "Vonetis Sea"},
  "Kagura": {"lane": ["Mid"], "role": ["Mage"], "region": "Cadia Riverlands"},
  "Kaja": {"lane": ["Roam"], "role": ["Fighter", "Support"], "region": "Vonetis Sea"},
  "Kalea": {"lane": ["Roam"], "role": ["Fighter", "Support"], "region": "Vonetis Sea"},
  "Karina": {"lane": ["Jungle"], "role": ["Assassin"], "region": "Azrya Woodlands"},
  "Karrie": {"lane": ["Gold"], "role": ["Marksman"], "region": "Vonetis Sea"},
  "Khaleed": {"lane": ["Roam"], "role": ["Fighter"], "region": "Agelta Drylands"},
  "Khufra": {"lane": ["Roam"], "role": ["Tank"], "region": "Agelta Drylands"},
  "Kimmy": {"lane": ["Mid"], "role": ["Mage", "Marksman"], "region": "Moniyan"},
  "Lancelot": {"lane": ["Jungle"], "role": ["Assassin"], "region": "Moniyan"},
  "Lapu-Lapu": {"lane": ["EXP"], "role": ["Fighter"], "region": "Vonetis Sea"},
  "Layla": {"lane": ["Gold"], "role": ["Marksman"], "region": "Agelta Drylands"},
  "Leomord": {"lane": ["Jungle"], "role": ["Fighter"], "region": "The Barren Lands"},
  "Lesley": {"lane": ["Gold"], "role": ["Assassin", "Marksman"], "region": "Moniyan"},
  "Ling": {"lane": ["Jungle"], "role": ["Assassin"], "region": "Cadia Riverlands"},
  "Lolita": {"lane": ["Roam"], "role": ["Support", "Tank"], "region": "Agelta Drylands"},
  "Lukas": {"lane": ["EXP"], "role": ["Fighter"], "region": "Moniyan"},
  "Lunox": {"lane": ["Mid"], "role": ["Mage"], "region": "Agelta Drylands"},
  "Luo Yi": {"lane": ["Mid"], "role": ["Mage"], "region": "Cadia Riverlands"},
  "Lylia": {"lane": ["Mid"], "role": ["Mage"], "region": "Northern Vale"},
  "Marcel": {"lane": ["Roam"], "role": ["Support"], "region": "Moniyan"},
  "Martis": {"lane": ["Jungle"], "role": ["Fighter"], "region": "Vonetis Sea"},
  "Masha": {"lane": ["EXP"], "role": ["Fighter", "Tank"], "region": "Northern Vale"},
  "Mathilda": {"lane": ["Roam"], "role": ["Assassin", "Support"], "region": "Agelta Drylands"},
  "Melissa": {"lane": ["Gold"], "role": ["Marksman"], "region": "Moniyan"},
  "Minotaur": {"lane": ["Roam"], "role": ["Tank", "Support"], "region": "Agelta Drylands"},
  "Minsitthar": {"lane": ["EXP"], "role": ["Fighter"], "region": "Vonetis Sea"},
  "Miya": {"lane": ["Gold"], "role": ["Marksman"], "region": "Azrya Woodlands"},
  "Moskov": {"lane": ["Gold"], "role": ["Marksman"], "region": "Agelta Drylands"},
  "Nana": {"lane": ["Mid"], "role": ["Mage"], "region": "Azrya Woodlands"},
  "Natalia": {"lane": ["Jungle"], "role": ["Assassin"], "region": "Moniyan"},
  "Natan": {"lane": ["Gold"], "role": ["Marksman"], "region": "Agelta Drylands"},
  "Nolan": {"lane": ["Jungle"], "role": ["Assassin"], "region": "Agelta Drylands"},
  "Novaria": {"lane": ["Mid"], "role": ["Mage"], "region": "Agelta Drylands"},
  "Obsidia": {"lane": ["Gold"], "role": ["Marksman"], "region": "Abyss"},
  "Odette": {"lane": ["Mid"], "role": ["Mage"], "region": "Moniyan"},
  "Paquito": {"lane": ["EXP"], "role": ["Fighter", "Assassin"], "region": "The Barren Lands"},
  "Pharsa": {"lane": ["Mid"], "role": ["Mage"], "region": "The Barren Lands"},
  "Phoveus": {"lane": ["EXP"], "role": ["Fighter"], "region": "The Barren Lands"},
  "Popol and Kupa": {"lane": ["Jungle"], "role": ["Marksman"], "region": "Northern Vale"},
  "Rafaela": {"lane": ["Roam"], "role": ["Support"], "region": "Moniyan"},
  "Roger": {"lane": ["Jungle"], "role": ["Fighter", "Marksman"], "region": "Moniyan"},
  "Ruby": {"lane": ["EXP"], "role": ["Fighter"], "region": "Moniyan"},
  "Saber": {"lane": ["Jungle"], "role": ["Assassin"], "region": "Agelta Drylands"},
  "Selena": {"lane": ["Mid"], "role": ["Mage", "Assassin"], "region": "Abyss"},
  "Silvanna": {"lane": ["EXP"], "role": ["Fighter"], "region": "Moniyan"},
  "Sora": {"lane": ["EXP"], "role": ["Fighter", "Assassin"], "region": "Agelta Drylands"},
  "Sun": {"lane": ["EXP"], "role": ["Fighter"], "region": "Cadia Riverlands"},
  "Suyou": {"lane": ["Jungle"], "role": ["Fighter", "Assassin"], "region": "Cadia Riverlands"},
  "Terizla": {"lane": ["EXP"], "role": ["Fighter", "Tank"], "region": "Abyss"},
  "Thamuz": {"lane": ["EXP"], "role": ["Fighter"], "region": "Abyss"},
  "Tigreal": {"lane": ["Roam"], "role": ["Tank"], "region": "Moniyan"},
  "Uranus": {"lane": ["EXP"], "role": ["Tank"], "region": "Vonetis Sea"},
  "Vale": {"lane": ["Mid"], "role": ["Mage"], "region": "Agelta Drylands"},
  "Valentina": {"lane": ["Mid"], "role": ["Mage"], "region": "Moniyan"},
  "Valir": {"lane": ["Mid"], "role": ["Mage"], "region": "Agelta Drylands"},
  "Vexana": {"lane": ["Mid"], "role": ["Mage"], "region": "The Barren Lands"},
  "Wanwan": {"lane": ["Gold"], "role": ["Marksman"], "region": "Cadia Riverlands"},
  "X.Borg": {"lane": ["EXP"], "role": ["Fighter"], "region": "Agelta Drylands"},
  "Xavier": {"lane": ["Mid"], "role": ["Mage"], "region": "Moniyan"},
  "Yi Sun-shin": {"lane": ["Jungle"], "role": ["Assassin", "Marksman"], "region": "Cadia Riverlands"},
  "Yin": {"lane": ["Jungle"], "role": ["Assassin", "Fighter"], "region": "Moniyan"},
  "Yu Zhong": {"lane": ["EXP"], "role": ["Fighter"], "region": "Cadia Riverlands"},
  "Yve": {"lane": ["Mid"], "role": ["Mage"], "region": "Vonetis Sea"},
  "Zetian": {"lane": ["Mid"], "role": ["Mage"], "region": "Cadia Riverlands"},
  "Zhask": {"lane": ["Mid"], "role": ["Mage"], "region": "Moniyan"},
  "Zhuxin": {"lane": ["Mid"], "role": ["Mage"], "region": "Cadia Riverlands"},
  "Zilong": {"lane": ["EXP"], "role": ["Assassin", "Fighter"], "region": "Cadia Riverlands"}
}
