ITEMS = {
    # ================= ATTACK =================
    "Berserker Fury": {"type": "attack", "tier": "full"},
    "Blade of Despair": {"type": "attack", "tier": "full"},
    "Blade of the Heptaseas": {"type": "attack", "tier": "full"},
    "Corrosion Scythe": {"type": "attack", "tier": "full"},
    "Demon Hunter Sword": {"type": "attack", "tier": "full"},
    "Endless Battle": {"type": "attack", "tier": "full"},
    "Golden Staff": {"type": "attack", "tier": "full"},
    "Great Dragon Spear": {"type": "attack", "tier": "full"},
    "Haas Claws": {"type": "attack", "tier": "full"},
    "Hunter Strike": {"type": "attack", "tier": "full"},
    "Malefic Roar": {"type": "attack", "tier": "full"},
    "Malefic Gun": {"type": "attack", "tier": "full"},
    "Rose Gold Meteor": {"type": "attack", "tier": "full"},
    "Sea Halberd": {"type": "attack", "tier": "full"},
    "War Axe": {"type": "attack", "tier": "full"},
    "Wind of Nature": {"type": "attack", "tier": "full"},
    "Windtalker": {"type": "attack", "tier": "full"},
    "Sky Piercer": {"type": "attack", "tier": "full"},

    # ATTACK BASIC
    "Fury Hammer": {"type": "attack", "tier": "basic"},
    "Legion Sword": {"type": "attack", "tier": "basic"},
    "Magic Blade": {"type": "attack", "tier": "basic"},
    "Ogre Tomahawk": {"type": "attack", "tier": "basic"},
    "Swift Crossbow": {"type": "attack", "tier": "basic"},
    "Dagger": {"type": "attack", "tier": "basic"},
    "Javelin": {"type": "attack", "tier": "basic"},
    "Regular Spear": {"type": "attack", "tier": "basic"},
    "Rogue Meteor": {"type": "attack", "tier": "basic"},
    "Iron Hunting Bow": {"type": "attack", "tier": "basic"},
    "Knife": {"type": "attack", "tier": "basic"},
    "Vampire Mallet": {"type": "attack", "tier": "basic"},

    # ================= MAGIC =================
    "Blood Wings": {"type": "magic", "tier": "full"},
    "Clock of Destiny": {"type": "magic", "tier": "full"},
    "Concentrated Energy": {"type": "magic", "tier": "full"},
    "Divine Glaive": {"type": "magic", "tier": "full"},
    "Enchanted Talisman": {"type": "magic", "tier": "full"},
    "Feather of Heaven": {"type": "magic", "tier": "full"},
    "Genius Wand": {"type": "magic", "tier": "full"},
    "Glowing Wand": {"type": "magic", "tier": "full"},
    "Holy Crystal": {"type": "magic", "tier": "full"},
    "Ice Queen Wand": {"type": "magic", "tier": "full"},
    "Lightning Truncheon": {"type": "magic", "tier": "full"},
    "Flask of the Oasis": {"type": "magic", "tier": "full"},
    "Starlium Scythe": {"type": "magic", "tier": "full"},
    "Wishing Lantern": {"type": "magic", "tier": "full"},
    "Winter Crown": {"type": "magic", "tier": "full"},

    # MAGIC BASIC
    "Azure Blade": {"type": "magic", "tier": "basic"},
    "Elegant Gem": {"type": "magic", "tier": "basic"},
    "Mystic Container": {"type": "magic", "tier": "basic"},
    "Tome of Evil": {"type": "magic", "tier": "basic"},
    "Magic Wand": {"type": "magic", "tier": "basic"},
    "Exotic Veil": {"type": "magic", "tier": "basic"},
    "Book of Sages": {"type": "magic", "tier": "basic"},
    "Magic Necklace": {"type": "magic", "tier": "basic"},
    "Mystery Codex": {"type": "magic", "tier": "basic"},
    "Power Crystal": {"type": "magic", "tier": "basic"},

    # ================= DEFENSE =================
    "Antique Cuirass": {"type": "defense", "tier": "full"},
    "Athena Shield": {"type": "defense", "tier": "full"},
    "Blade Armor": {"type": "defense", "tier": "full"},
    "Brute Force Breastplate": {"type": "defense", "tier": "full"},
    "Cursed Helmet": {"type": "defense", "tier": "full"},
    "Dominance Ice": {"type": "defense", "tier": "full"},
    "Guardian Helmet": {"type": "defense", "tier": "full"},
    "Immortality": {"type": "defense", "tier": "full"},
    "Oracle": {"type": "defense", "tier": "full"},
    "Radiant Armor": {"type": "defense", "tier": "full"},
    "Thunder Belt": {"type": "defense", "tier": "full"},
    "Queen Wings": {"type": "defense", "tier": "full"},

    # DEFENSE BASIC
    "Ares Belt": {"type": "defense", "tier": "basic"},
    "Dreadnaught Armor": {"type": "defense", "tier": "basic"},
    "Molten Essence": {"type": "defense", "tier": "basic"},
    "Steel Legplates": {"type": "defense", "tier": "basic"},
    "Vitality Crystal": {"type": "defense", "tier": "basic"},
    "Black Ice Shield": {"type": "defense", "tier": "basic"},
    "Silence Robe": {"type": "defense", "tier": "basic"},
    "Magic Resist Cloak": {"type": "defense", "tier": "basic"},
    "Leather Jerkin": {"type": "defense", "tier": "basic"},
    "Hero Ring": {"type": "defense", "tier": "basic"},
    "Healing Necklace": {"type": "defense", "tier": "basic"},

    # ================= BOOTS =================
    "Arcane Boots": {"type": "boots"},
    "Demon Boots": {"type": "boots"},
    "Magic Boots": {"type": "boots"},
    "Rapid Boots": {"type": "boots"},
    "Swift Boots": {"type": "boots"},
    "Tough Boots": {"type": "boots"},
    "Warrior Boots": {"type": "boots"},
    "Boots": {"type": "boots"},

    # ================= JUNGLE =================
    "Bloody Retribution": {"type": "jungle"},
    "Flame Retribution": {"type": "jungle"},
    "Ice Retribution": {"type": "jungle"},

    # ================= ROAM =================
    "Conceal": {"type": "roam"},
    "Dire Hit": {"type": "roam"},
    "Encourage": {"type": "roam"},
    "Favor": {"type": "roam"},
}
